graph LR
    subgraph VALIDATE
        direction LR
        fmt_check["fmt_check"]
        validate["validate"]
    end

    subgraph PLAN
        direction LR
        plan["plan"]
    end

    subgraph APPLY
        direction LR
        apply["apply ✋"]
    end

    subgraph DESTROY_PLAN
        direction LR
        destroy_plan["destroy_plan ✋"]
    end

    subgraph DESTROY
        direction LR
        destroy["destroy ✋"]
    end

    VALIDATE --> PLAN
    PLAN --> APPLY

    destroy_plan --> DESTROY

    plan -- tfplan (expires 1 day) .-> APPLY
    destroy_plan -- destroyplan (expires 1 day) .-> DESTROY

    style VALIDATE fill:#fff,stroke:#333,stroke-width:2px,stroke-dasharray: 5 5
    style PLAN fill:#fff,stroke:#333,stroke-width:2px,stroke-dasharray: 5 5
    style APPLY fill:#fff,stroke:#333,stroke-width:2px,stroke-dasharray: 5 5
    style DESTROY_PLAN fill:#fff,stroke:#333,stroke-width:2px,stroke-dasharray: 5 5
    style DESTROY fill:#fff,stroke:#333,stroke-width:2px,stroke-dasharray: 5 5

    linkStyle 0 stroke:#333,stroke-width:2px,stroke-dasharray: 5 5
    linkStyle 1 stroke:#333,stroke-width:2px,stroke-dasharray: 5 5
    linkStyle 2 stroke:#333,stroke-width:2px,stroke-dasharray: 5 5
    linkStyle 3 stroke:#333,stroke-width:2px,stroke-dasharray: 5 5
    linkStyle 4 stroke:#333,stroke-width:2px,stroke-dasharray: 5 5